INSERT INTO "location"
(country_name, region_name, major_city)
VALUES('POLSKA', 'WOJ. DOLNOŚLĄSKIE', 'WROCŁAW');

INSERT INTO "location"
(country_name, region_name, major_city)
VALUES('POLSKA', 'WOJ. MAZOWIECKIE', 'WARSZAWA');

insert into "location" (country_name, region_name, major_city) values ('France', 'Poitou-Charentes', 'Niort');
insert into "location" (country_name, region_name, major_city) values ('Spain', 'Murcia', 'Murcia');
insert into "location" (country_name, region_name, major_city) values ('France', 'Île-de-France', 'Sartrouville');
insert into "location" (country_name, region_name, major_city) values ('United States', 'Arkansas', 'North Little Rock');
insert into "location" (country_name, region_name, major_city) values ('United States', 'Texas', 'Houston');
insert into "location" (country_name, region_name, major_city) values ('France', 'Île-de-France', 'Antony');
insert into "location" (country_name, region_name, major_city) values ('United States', 'Louisiana', 'Shreveport');
insert into "location" (country_name, region_name, major_city) values ('United States', 'Texas', 'Corpus Christi');
insert into "location" (country_name, region_name, major_city) values ('France', 'Centre', 'Tours');
insert into "location" (country_name, region_name, major_city) values ('France', 'Alsace', 'Mulhouse');
insert into "location" (country_name, region_name, major_city) values ('France', 'Languedoc-Roussillon', 'Montpellier');
insert into "location" (country_name, region_name, major_city) values ('United States', 'Oklahoma', 'Tulsa');
insert into "location" (country_name, region_name, major_city) values ('France', 'Île-de-France', 'Orly aérogare');
insert into "location" (country_name, region_name, major_city) values ('France', 'Midi-Pyrénées', 'Toulouse');
insert into "location" (country_name, region_name, major_city) values ('France', 'Île-de-France', 'Morangis');
insert into "location" (country_name, region_name, major_city) values ('Germany', 'Sachsen', 'Leipzig');
insert into "location" (country_name, region_name, major_city) values ('United States', 'Alabama', 'Mobile');
insert into "location" (country_name, region_name, major_city) values ('France', 'Île-de-France', 'Paris La Défense');
insert into "location" (country_name, region_name, major_city) values ('United States', 'Georgia', 'Atlanta');
insert into "location" (country_name, region_name, major_city) values ('United States', 'Florida', 'Port Saint Lucie');
insert into "location" (country_name, region_name, major_city) values ('United States', 'California', 'Pasadena');
insert into "location" (country_name, region_name, major_city) values ('France', 'Rhône-Alpes', 'Décines-Charpieu');
insert into "location" (country_name, region_name, major_city) values ('United States', 'Pennsylvania', 'Erie');
insert into "location" (country_name, region_name, major_city) values ('France', 'Bourgogne', 'Mâcon');
insert into "location" (country_name, region_name, major_city) values ('France', 'Île-de-France', 'Paris 02');
insert into "location" (country_name, region_name, major_city) values ('United States', 'Ohio', 'Toledo');
insert into "location" (country_name, region_name, major_city) values ('United States', 'Ohio', 'Hamilton');
insert into "location" (country_name, region_name, major_city) values ('France', 'Lorraine', 'Montigny-lès-Metz');
insert into "location" (country_name, region_name, major_city) values ('France', 'Auvergne', 'Clermont-Ferrand');
insert into "location" (country_name, region_name, major_city) values ('United States', 'Florida', 'Miami');
insert into "location" (country_name, region_name, major_city) values ('France', 'Île-de-France', 'Cergy-Pontoise');
insert into "location" (country_name, region_name, major_city) values ('United States', 'Virginia', 'Newport News');
insert into "location" (country_name, region_name, major_city) values ('United States', 'Florida', 'Tampa');
insert into "location" (country_name, region_name, major_city) values ('United States', 'Colorado', 'Greeley');
insert into "location" (country_name, region_name, major_city) values ('France', 'Alsace', 'Colmar');
insert into "location" (country_name, region_name, major_city) values ('United States', 'Florida', 'Orlando');
insert into "location" (country_name, region_name, major_city) values ('United States', 'California', 'San Diego');
insert into "location" (country_name, region_name, major_city) values ('France', 'Languedoc-Roussillon', 'Nîmes');
insert into "location" (country_name, region_name, major_city) values ('United States', 'California', 'Sacramento');
insert into "location" (country_name, region_name, major_city) values ('United States', 'Colorado', 'Colorado Springs');
insert into "location" (country_name, region_name, major_city) values ('United Kingdom', 'England', 'Ford');
insert into "location" (country_name, region_name, major_city) values ('France', 'Île-de-France', 'Pantin');
insert into "location" (country_name, region_name, major_city) values ('United States', 'Texas', 'Dallas');
insert into "location" (country_name, region_name, major_city) values ('United States', 'Connecticut', 'Stamford');
insert into "location" (country_name, region_name, major_city) values ('United Kingdom', 'England', 'Swindon');
insert into "location" (country_name, region_name, major_city) values ('France', 'Nord-Pas-de-Calais', 'Saint-Amand-les-Eaux');
insert into "location" (country_name, region_name, major_city) values ('France', 'Île-de-France', 'Noisy-le-Grand');
insert into "location" (country_name, region_name, major_city) values ('United States', 'Virginia', 'Merrifield');
insert into "location" (country_name, region_name, major_city) values ('Spain', 'Navarra', 'Pamplona/Iruña');
insert into "location" (country_name, region_name, major_city) values ('United Kingdom', 'England', 'Leeds');
insert into "location" (country_name, region_name, major_city) values ('France', 'Centre', 'Issoudun');
insert into "location" (country_name, region_name, major_city) values ('United States', 'Arizona', 'Phoenix');
insert into "location" (country_name, region_name, major_city) values ('United States', 'Georgia', 'Atlanta');
insert into "location" (country_name, region_name, major_city) values ('France', 'Midi-Pyrénées', 'Toulouse');
insert into "location" (country_name, region_name, major_city) values ('France', 'Île-de-France', 'Cergy-Pontoise');
insert into "location" (country_name, region_name, major_city) values ('United States', 'Oklahoma', 'Oklahoma City');
insert into "location" (country_name, region_name, major_city) values ('France', 'Rhône-Alpes', 'La Motte-Servolex');
insert into "location" (country_name, region_name, major_city) values ('France', 'Rhône-Alpes', 'Annonay');
insert into "location" (country_name, region_name, major_city) values ('France', 'Languedoc-Roussillon', 'Montpellier');
insert into "location" (country_name, region_name, major_city) values ('France', 'Île-de-France', 'Paris La Défense');
insert into "location" (country_name, region_name, major_city) values ('United States', 'Hawaii', 'Honolulu');
insert into "location" (country_name, region_name, major_city) values ('France', 'Midi-Pyrénées', 'Cahors');
insert into "location" (country_name, region_name, major_city) values ('United States', 'Texas', 'Dallas');
insert into "location" (country_name, region_name, major_city) values ('Spain', 'Madrid', 'Leganes');
insert into "location" (country_name, region_name, major_city) values ('United States', 'South Dakota', 'Sioux Falls');
insert into "location" (country_name, region_name, major_city) values ('Spain', 'Cataluna', 'Hospitalet De Llobregat, L''');
insert into "location" (country_name, region_name, major_city) values ('France', 'Languedoc-Roussillon', 'Montpellier');
insert into "location" (country_name, region_name, major_city) values ('France', 'Île-de-France', 'Paris 05');
insert into "location" (country_name, region_name, major_city) values ('France', 'Alsace', 'Strasbourg');
insert into "location" (country_name, region_name, major_city) values ('United Kingdom', 'England', 'London');
insert into "location" (country_name, region_name, major_city) values ('France', 'Rhône-Alpes', 'Lyon');
insert into "location" (country_name, region_name, major_city) values ('United States', 'Ohio', 'Hamilton');
insert into "location" (country_name, region_name, major_city) values ('United States', 'Illinois', 'Springfield');
insert into "location" (country_name, region_name, major_city) values ('France', 'Nord-Pas-de-Calais', 'Lomme');
insert into "location" (country_name, region_name, major_city) values ('France', 'Rhône-Alpes', 'Vienne');
insert into "location" (country_name, region_name, major_city) values ('United States', 'Washington', 'Olympia');
insert into "location" (country_name, region_name, major_city) values ('United States', 'Arkansas', 'Fort Smith');
insert into "location" (country_name, region_name, major_city) values ('France', 'Provence-Alpes-Côte d''Azur', 'Marseille');
insert into "location" (country_name, region_name, major_city) values ('Germany', 'Bremen', 'Bremen');
insert into "location" (country_name, region_name, major_city) values ('France', 'Alsace', 'Schiltigheim');
insert into "location" (country_name, region_name, major_city) values ('France', 'Haute-Normandie', 'Rouen');
insert into "location" (country_name, region_name, major_city) values ('United States', 'Nevada', 'Las Vegas');
insert into "location" (country_name, region_name, major_city) values ('United States', 'Texas', 'Dallas');
insert into "location" (country_name, region_name, major_city) values ('United States', 'Missouri', 'Springfield');
insert into "location" (country_name, region_name, major_city) values ('France', 'Provence-Alpes-Côte d''Azur', 'Carpentras');
insert into "location" (country_name, region_name, major_city) values ('United States', 'Georgia', 'Atlanta');
insert into "location" (country_name, region_name, major_city) values ('Germany', 'Nordrhein-Westfalen', 'Köln');
insert into "location" (country_name, region_name, major_city) values ('France', 'Île-de-France', 'Longjumeau');
insert into "location" (country_name, region_name, major_city) values ('United States', 'Montana', 'Billings');
insert into "location" (country_name, region_name, major_city) values ('France', 'Aquitaine', 'Bergerac');
insert into "location" (country_name, region_name, major_city) values ('Spain', 'Cantabria', 'Santander');
insert into "location" (country_name, region_name, major_city) values ('United Kingdom', 'Scotland', 'Milton');
insert into "location" (country_name, region_name, major_city) values ('France', 'Bretagne', 'Saint-Brieuc');
insert into "location" (country_name, region_name, major_city) values ('United States', 'Texas', 'San Antonio');
insert into "location" (country_name, region_name, major_city) values ('France', 'Île-de-France', 'Paris 03');
insert into "location" (country_name, region_name, major_city) values ('France', 'Centre', 'Orléans');
insert into "location" (country_name, region_name, major_city) values ('France', 'Île-de-France', 'Marne-la-Vallée');
insert into "location" (country_name, region_name, major_city) values ('France', 'Rhône-Alpes', 'Grenoble');
insert into "location" (country_name, region_name, major_city) values ('France', 'Provence-Alpes-Côte d''Azur', 'Marseille');
insert into "location" (country_name, region_name, major_city) values ('United States', 'Alabama', 'Mobile');
