insert into nationality (nationality_name) values ('Russia');
insert into nationality (nationality_name) values ('Poland');
insert into nationality (nationality_name) values ('Nigeria');
insert into nationality (nationality_name) values ('Costa Rica');
insert into nationality (nationality_name) values ('France');
insert into nationality (nationality_name) values ('United States');
insert into nationality (nationality_name) values ('Portugal');
insert into nationality (nationality_name) values ('Canada');
insert into nationality (nationality_name) values ('Ireland');
insert into nationality (nationality_name) values ('Jamaica');
insert into nationality (nationality_name) values ('Greece');
insert into nationality (nationality_name) values ('Philippines');
insert into nationality (nationality_name) values ('Thailand');
insert into nationality (nationality_name) values ('Indonesia');
insert into nationality (nationality_name) values ('Argentina');
insert into nationality (nationality_name) values ('China');
insert into nationality (nationality_name) values ('Sweden');
insert into nationality (nationality_name) values ('Czech Republic');
insert into nationality (nationality_name) values ('South Korea');