drop table if exists
"location", base, operation, operation_history,
personel, soldier, soldier_history, "role", nationality,
team, weapon, vehicle_type, vehicle, team_operation cascade;

create table nationality(
	id bigint not null generated by default as identity (start with 1),
	nationality_name varchar unique check(char_length(nationality_name) <= 100),
	primary key(id)
);

create table "location"(
	id bigint not null generated by default as identity (start with 1),
	country_name varchar check(char_length(country_name) <= 200),
	region_name varchar check(char_length(region_name) <= 300),
	major_city varchar check(char_length(major_city) <= 300),
	primary key(id)
);

create table "role"(
	id bigint not null generated by default as identity (start with 1),
	role_name varchar check(char_length(role_name) <= 100),
	primary key(id)
);

create table base(
	id bigint not null generated by default as identity (start with 1),
	base_name varchar default 'BASE-UNNAMED',
	location_id bigint not null,
	cheef_id bigint,
	personel_count bigint check(personel_count >= 0) default 0,
	primary key(id),
	foreign key(location_id) references "location"(id)
		on update cascade
);

create table personel(
	id bigint not null generated by default as identity (start with 1),
	first_name varchar check(char_length(first_name) <= 255),
	last_name varchar check(char_length(last_name) <= 255),
	hire_date date check(hire_date <= current_date),
	on_leave boolean default false,
	base_id bigint,
	role_id bigint,
	primary key(id),
	foreign key(base_id) references base(id)
		on update cascade on delete set null,
	foreign key(role_id) references "role"(id)
		on update cascade on delete set null
);

alter table base
add foreign key(cheef_id) references personel(id)
	on update cascade;

create table operation(
	id bigint not null generated by default as identity (start with 1),
	location_id bigint,
	title varchar check(char_length(title) <= 500),
	start_date timestamptz,
	primary key(id),
	foreign key(location_id) references "location"(id)
		on update cascade
);

create table operation_history(
	id bigint not null generated by default as identity (start with 1),
	location_id bigint,
	title varchar check(char_length(title) <= 500),
	start_date timestamptz check(start_date <= now()),
	end_date timestamptz check(end_date <= now()),
	check (start_date < end_date),
	teams_involved varchar check(char_length(teams_involved) <= 2000),
	"result" varchar check(char_length("result") <= 500),
	total_cost numeric check(total_cost >= 0),
	primary key(id),
	foreign key(location_id) references "location"(id)
		on update cascade
);

create table team(
	id bigint not null generated by default as identity (start with 1),
	team_name varchar check(char_length(team_name) <= 255),
	leader_id bigint,
	base_id bigint,
	primary key(id),
	foreign key(leader_id) references personel(id)
		on update cascade on delete set null,
	foreign key(base_id) references base(id)
		on update cascade
);

create table team_operation(
	id bigint not null generated by default as identity (start with 1),
	operation_id bigint,
	team_id bigint,
	primary key(id),
	foreign key(operation_id) references operation(id)
		on update cascade,
	foreign key(team_id) references team(id)
		on update cascade
);

create table soldier(
	id bigint not null,
	team_id bigint,
	nationality_id int,
	soldier_rank varchar check(char_length(soldier_rank) <= 255),
	in_operation boolean default false,
	primary key(id),
	foreign key(id) references personel(id)
		on update cascade,
	foreign key(team_id) references team(id)
		on update cascade,
	foreign key(nationality_id) references nationality(id)
		on update cascade on delete set null
);

create table soldier_history(
	id bigint not null generated by default as identity (start with 1),
	soldier_rank varchar check(char_length(soldier_rank) <= 255),
	operation_count int check(operation_count >= 0),
	first_name varchar check(char_length(first_name) <= 255),
	last_name varchar check(char_length(last_name) <= 255),
	nationality_id int,
	duty_start_date date check(duty_start_date <= current_date),
	duty_end_date date check(duty_end_date <= current_date),
	check(duty_start_date < duty_end_date),
	kia boolean not null,
	primary key(id),
	foreign key(nationality_id) references nationality(id)
		on update cascade on delete set null
);

create table weapon(
	id bigint not null generated by default as identity (start with 1),
	team_id bigint,
	model_name varchar check(char_length(model_name) <= 255),
	money_value numeric check(money_value >= 0),
	amount bigint check(amount > 0),
	primary key(id),
	foreign key(team_id) references team(id)
		on update cascade
);

create table vehicle_type(
	id bigint not null generated by default as identity (start with 1),
	type_name varchar check(char_length(type_name) <= 255),
	primary key(id)
);

create table vehicle(
	id bigint not null generated by default as identity (start with 1),
	team_id bigint,
	model_name varchar check(char_length(model_name) <= 255),
	money_value numeric check(money_value >= 0),
	amount bigint check(amount > 0),
	type_id bigint,
	primary key(id),
	foreign key(team_id) references team(id)
		on update cascade,
	foreign key(type_id) references vehicle_type(id)
		on update cascade
);

