insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1, null, 17, 'Generał', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (4, null, 15, 'Plutonowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (7, null, 14, 'Starszy sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (10, null, 8, 'Szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (13, null, 13, 'Kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (16, null, 6, 'Starszy sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (19, null, 11, 'Porucznik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (22, null, 2, 'Generał dywizji', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (25, null, 17, 'Kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (28, null, 10, 'Młodszy podchorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (31, null, 2, 'Kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (34, null, 8, 'Generał', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (37, null, 2, 'Chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (40, null, 9, 'Podpułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (43, null, 7, 'Porucznik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (46, null, 10, 'Starszy sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (49, null, 14, 'Kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (52, null, 16, 'Pułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (55, null, 6, 'Kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (58, null, 12, 'Starszy szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (61, null, 17, 'Starszy szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (64, null, 6, 'Starszy chorąży sztabowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (67, null, 17, 'Młodszy podchorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (70, null, 4, 'Generał broni', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (73, null, 11, 'Starszy kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (76, null, 2, 'Generał brygady', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (79, null, 14, 'Starszy chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (82, null, 1, 'Podpułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (85, null, 11, 'Szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (88, null, 3, 'Starszy chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (91, null, 17, 'Starszy chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (94, null, 12, 'Porucznik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (97, null, 14, 'Generał broni', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (100, null, 4, 'Starszy chorąży sztabowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (103, null, 6, 'Starszy chorąży sztabowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (106, null, 13, 'Starszy szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (109, null, 15, 'Porucznik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (112, null, 8, 'Kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (115, null, 11, 'Starszy kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (118, null, 3, 'Kapitan', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (121, null, 15, 'Starszy szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (124, null, 3, 'Generał broni', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (127, null, 9, 'Generał', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (130, null, 19, 'Podpułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (133, null, 4, 'Starszy szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (136, null, 19, 'Pułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (139, null, 10, 'Generał brygady', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (142, null, 14, 'Podporucznik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (145, null, 2, 'Starszy szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (148, null, 17, 'Młodszy podchorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (151, null, 1, 'Plutonowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (154, null, 11, 'Major', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (157, null, 8, 'Plutonowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (160, null, 4, 'Pułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (163, null, 19, 'Pułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (166, null, 9, 'Starszy chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (169, null, 7, 'Młodszy podchorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (172, null, 14, 'Starszy sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (175, null, 4, 'Plutonowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (178, null, 2, 'Major', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (181, null, 11, 'Generał broni', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (184, null, 10, 'Pułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (187, null, 4, 'Generał broni', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (190, null, 13, 'Podpułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (193, null, 11, 'Porucznik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (196, null, 9, 'Starszy chorąży sztabowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (199, null, 14, 'Generał dywizji', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (202, null, 19, 'Generał', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (205, null, 5, 'Generał brygady', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (208, null, 16, 'Starszy kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (211, null, 12, 'Generał dywizji', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (214, null, 6, 'Kapitan', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (217, null, 5, 'Starszy sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (220, null, 16, 'Szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (223, null, 8, 'Kapitan', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (226, null, 9, 'Kapitan', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (229, null, 1, 'Chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (232, null, 17, 'Kapitan', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (235, null, 1, 'Generał dywizji', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (238, null, 13, 'Porucznik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (241, null, 10, 'Chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (244, null, 7, 'Generał brygady', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (247, null, 2, 'Porucznik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (250, null, 5, 'Starszy sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (253, null, 11, 'Plutonowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (256, null, 8, 'Podpułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (259, null, 5, 'Starszy szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (262, null, 11, 'Kapitan', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (265, null, 5, 'Generał broni', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (268, null, 18, 'Porucznik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (271, null, 14, 'Starszy chorąży sztabowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (274, null, 12, 'Starszy szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (277, null, 10, 'Chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (280, null, 3, 'Generał', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (283, null, 12, 'Generał', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (286, null, 15, 'Generał dywizji', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (289, null, 2, 'Starszy chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (292, null, 3, 'Generał brygady', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (295, null, 14, 'Starszy szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (298, null, 3, 'Podporucznik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (301, null, 14, 'Starszy kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (304, null, 9, 'Starszy chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (307, null, 16, 'Generał dywizji', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (310, null, 10, 'Major', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (313, null, 5, 'Kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (316, null, 14, 'Starszy chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (319, null, 2, 'Starszy kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (322, null, 19, 'Kapitan', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (325, null, 4, 'Plutonowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (328, null, 4, 'Generał dywizji', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (331, null, 4, 'Generał', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (334, null, 17, 'Starszy szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (337, null, 15, 'Szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (340, null, 3, 'Generał brygady', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (343, null, 9, 'Generał brygady', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (346, null, 15, 'Podpułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (349, null, 18, 'Podpułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (352, null, 11, 'Plutonowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (355, null, 18, 'Podpułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (358, null, 10, 'Major', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (361, null, 14, 'Generał', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (364, null, 9, 'Starszy sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (367, null, 7, 'Plutonowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (370, null, 11, 'Generał', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (373, null, 2, 'Generał', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (376, null, 16, 'Major', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (379, null, 4, 'Starszy szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (382, null, 1, 'Chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (385, null, 10, 'Plutonowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (388, null, 10, 'Starszy kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (391, null, 2, 'Kapitan', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (394, null, 18, 'Starszy kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (397, null, 8, 'Starszy szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (400, null, 11, 'Pułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (403, null, 9, 'Kapitan', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (406, null, 2, 'Starszy sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (409, null, 5, 'Generał broni', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (412, null, 9, 'Porucznik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (415, null, 19, 'Generał brygady', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (418, null, 9, 'Szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (421, null, 11, 'Kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (424, null, 6, 'Generał brygady', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (427, null, 2, 'Starszy chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (430, null, 19, 'Starszy kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (433, null, 7, 'Starszy sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (436, null, 1, 'Podpułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (439, null, 10, 'Plutonowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (442, null, 2, 'Starszy chorąży sztabowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (445, null, 6, 'Chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (448, null, 14, 'Starszy chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (451, null, 9, 'Major', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (454, null, 11, 'Chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (457, null, 18, 'Podpułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (460, null, 17, 'Pułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (463, null, 2, 'Starszy chorąży sztabowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (466, null, 8, 'Starszy sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (469, null, 11, 'Starszy sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (472, null, 10, 'Sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (475, null, 19, 'Podpułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (478, null, 12, 'Młodszy podchorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (481, null, 14, 'Generał broni', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (484, null, 1, 'Podpułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (487, null, 11, 'Podporucznik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (490, null, 19, 'Generał broni', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (493, null, 9, 'Starszy szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (496, null, 18, 'Starszy chorąży sztabowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (499, null, 11, 'Starszy sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (502, null, 10, 'Generał', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (505, null, 15, 'Szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (508, null, 4, 'Starszy kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (511, null, 9, 'Podpułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (514, null, 8, 'Major', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (517, null, 3, 'Sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (520, null, 10, 'Starszy chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (523, null, 4, 'Kapitan', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (526, null, 16, 'Kapitan', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (529, null, 15, 'Starszy chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (532, null, 18, 'Szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (535, null, 10, 'Szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (538, null, 10, 'Szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (541, null, 4, 'Starszy szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (544, null, 11, 'Starszy chorąży sztabowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (547, null, 19, 'Szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (550, null, 7, 'Starszy chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (553, null, 11, 'Sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (556, null, 5, 'Pułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (559, null, 2, 'Młodszy podchorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (562, null, 12, 'Starszy sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (565, null, 11, 'Podporucznik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (568, null, 2, 'Sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (571, null, 18, 'Generał', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (574, null, 6, 'Podpułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (577, null, 10, 'Podpułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (580, null, 6, 'Młodszy podchorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (583, null, 6, 'Plutonowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (586, null, 14, 'Generał dywizji', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (589, null, 10, 'Starszy sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (592, null, 18, 'Starszy sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (595, null, 4, 'Porucznik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (598, null, 12, 'Plutonowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (601, null, 16, 'Major', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (604, null, 12, 'Starszy sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (607, null, 19, 'Podporucznik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (610, null, 6, 'Starszy szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (613, null, 8, 'Młodszy podchorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (616, null, 1, 'Sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (619, null, 18, 'Chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (622, null, 9, 'Starszy sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (625, null, 12, 'Kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (628, null, 17, 'Porucznik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (631, null, 7, 'Podpułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (634, null, 12, 'Młodszy podchorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (637, null, 12, 'Starszy chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (640, null, 18, 'Szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (643, null, 14, 'Pułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (646, null, 13, 'Chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (649, null, 9, 'Starszy kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (652, null, 9, 'Podporucznik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (655, null, 10, 'Generał broni', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (658, null, 11, 'Szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (661, null, 4, 'Pułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (664, null, 19, 'Kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (667, null, 9, 'Starszy szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (670, null, 18, 'Porucznik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (673, null, 15, 'Starszy chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (676, null, 4, 'Podpułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (679, null, 11, 'Starszy sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (682, null, 2, 'Starszy szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (685, null, 7, 'Generał brygady', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (688, null, 19, 'Starszy sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (691, null, 12, 'Plutonowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (694, null, 16, 'Pułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (697, null, 4, 'Generał dywizji', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (700, null, 6, 'Kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (703, null, 15, 'Kapitan', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (706, null, 15, 'Starszy szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (709, null, 1, 'Pułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (712, null, 15, 'Generał brygady', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (715, null, 11, 'Podporucznik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (718, null, 6, 'Generał dywizji', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (721, null, 7, 'Szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (724, null, 1, 'Starszy sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (727, null, 9, 'Starszy chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (730, null, 15, 'Sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (733, null, 11, 'Generał broni', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (736, null, 16, 'Generał brygady', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (739, null, 13, 'Starszy szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (742, null, 1, 'Generał', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (745, null, 16, 'Generał dywizji', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (748, null, 6, 'Chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (751, null, 19, 'Szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (754, null, 1, 'Generał dywizji', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (757, null, 11, 'Generał brygady', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (760, null, 8, 'Młodszy podchorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (763, null, 15, 'Generał', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (766, null, 15, 'Generał brygady', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (769, null, 5, 'Starszy szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (772, null, 1, 'Starszy szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (775, null, 19, 'Plutonowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (778, null, 2, 'Generał dywizji', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (781, null, 3, 'Pułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (784, null, 15, 'Plutonowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (787, null, 5, 'Starszy kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (790, null, 15, 'Kapitan', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (793, null, 14, 'Podpułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (796, null, 11, 'Generał dywizji', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (799, null, 12, 'Generał dywizji', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (802, null, 12, 'Starszy chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (805, null, 16, 'Podporucznik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (808, null, 17, 'Sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (811, null, 13, 'Kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (814, null, 4, 'Pułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (817, null, 8, 'Major', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (820, null, 8, 'Plutonowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (823, null, 18, 'Szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (826, null, 17, 'Podpułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (829, null, 3, 'Generał brygady', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (832, null, 10, 'Generał brygady', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (835, null, 8, 'Plutonowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (838, null, 3, 'Podpułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (841, null, 5, 'Porucznik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (844, null, 14, 'Młodszy podchorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (847, null, 16, 'Porucznik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (850, null, 5, 'Pułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (853, null, 11, 'Plutonowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (856, null, 16, 'Starszy kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (859, null, 13, 'Generał dywizji', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (862, null, 18, 'Starszy kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (865, null, 18, 'Młodszy podchorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (868, null, 19, 'Starszy sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (871, null, 7, 'Podpułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (874, null, 17, 'Starszy chorąży sztabowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (877, null, 3, 'Kapitan', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (880, null, 19, 'Generał', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (883, null, 1, 'Sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (886, null, 16, 'Kapitan', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (889, null, 8, 'Starszy kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (892, null, 10, 'Generał brygady', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (895, null, 5, 'Starszy chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (898, null, 8, 'Podpułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (901, null, 10, 'Starszy sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (904, null, 7, 'Kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (907, null, 18, 'Młodszy podchorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (910, null, 15, 'Starszy sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (913, null, 3, 'Młodszy podchorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (916, null, 19, 'Chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (919, null, 6, 'Podpułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (922, null, 13, 'Generał broni', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (925, null, 6, 'Szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (928, null, 10, 'Chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (931, null, 16, 'Porucznik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (934, null, 1, 'Młodszy podchorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (937, null, 2, 'Starszy szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (940, null, 14, 'Kapitan', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (943, null, 17, 'Sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (946, null, 18, 'Młodszy podchorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (949, null, 19, 'Kapitan', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (952, null, 6, 'Podporucznik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (955, null, 16, 'Starszy kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (958, null, 5, 'Generał broni', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (961, null, 17, 'Starszy chorąży sztabowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (964, null, 10, 'Sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (967, null, 1, 'Kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (970, null, 5, 'Starszy chorąży sztabowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (973, null, 15, 'Starszy chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (976, null, 1, 'Kapitan', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (979, null, 2, 'Podpułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (982, null, 12, 'Chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (985, null, 5, 'Chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (988, null, 18, 'Generał dywizji', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (991, null, 10, 'Młodszy podchorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (994, null, 15, 'Starszy kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (997, null, 17, 'Szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1000, null, 9, 'Starszy kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1003, null, 19, 'Pułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1006, null, 12, 'Kapitan', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1009, null, 11, 'Chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1012, null, 6, 'Chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1015, null, 2, 'Porucznik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1018, null, 14, 'Starszy chorąży sztabowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1021, null, 3, 'Generał dywizji', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1024, null, 17, 'Generał brygady', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1027, null, 16, 'Starszy sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1030, null, 16, 'Młodszy podchorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1033, null, 5, 'Starszy chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1036, null, 18, 'Chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1039, null, 16, 'Major', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1042, null, 10, 'Młodszy podchorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1045, null, 17, 'Plutonowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1048, null, 3, 'Starszy sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1051, null, 17, 'Starszy kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1054, null, 13, 'Generał broni', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1057, null, 1, 'Chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1060, null, 14, 'Starszy sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1063, null, 8, 'Starszy chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1066, null, 3, 'Młodszy podchorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1069, null, 15, 'Plutonowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1072, null, 15, 'Kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1075, null, 17, 'Generał', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1078, null, 8, 'Generał broni', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1081, null, 11, 'Chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1084, null, 13, 'Generał dywizji', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1087, null, 9, 'Starszy sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1090, null, 2, 'Pułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1093, null, 12, 'Kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1096, null, 7, 'Kapitan', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1099, null, 11, 'Plutonowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1102, null, 11, 'Kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1105, null, 8, 'Pułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1108, null, 15, 'Generał', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1111, null, 5, 'Generał broni', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1114, null, 14, 'Starszy chorąży sztabowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1117, null, 11, 'Szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1120, null, 3, 'Sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1123, null, 15, 'Generał dywizji', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1126, null, 2, 'Starszy chorąży sztabowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1129, null, 4, 'Młodszy podchorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1132, null, 3, 'Kapitan', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1135, null, 5, 'Starszy szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1138, null, 18, 'Sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1141, null, 17, 'Podpułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1144, null, 15, 'Generał dywizji', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1147, null, 4, 'Starszy chorąży sztabowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1150, null, 10, 'Kapitan', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1153, null, 12, 'Generał brygady', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1156, null, 10, 'Starszy szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1159, null, 12, 'Kapitan', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1162, null, 6, 'Kapitan', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1165, null, 14, 'Generał', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1168, null, 11, 'Starszy kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1171, null, 1, 'Plutonowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1174, null, 9, 'Pułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1177, null, 15, 'Młodszy podchorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1180, null, 4, 'Młodszy podchorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1183, null, 14, 'Starszy sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1186, null, 8, 'Starszy chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1189, null, 12, 'Plutonowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1192, null, 17, 'Podpułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1195, null, 19, 'Starszy chorąży sztabowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1198, null, 7, 'Podporucznik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1201, null, 17, 'Starszy sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1204, null, 17, 'Plutonowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1207, null, 16, 'Młodszy podchorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1210, null, 2, 'Major', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1213, null, 5, 'Starszy chorąży sztabowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1216, null, 5, 'Generał brygady', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1219, null, 16, 'Młodszy podchorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1222, null, 3, 'Młodszy podchorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1225, null, 1, 'Starszy kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1228, null, 16, 'Major', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1231, null, 15, 'Starszy sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1234, null, 3, 'Podporucznik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1237, null, 3, 'Starszy sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1240, null, 8, 'Starszy chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1243, null, 19, 'Starszy szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1246, null, 3, 'Młodszy podchorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1249, null, 4, 'Starszy szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1252, null, 10, 'Podpułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1255, null, 19, 'Major', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1258, null, 6, 'Major', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1261, null, 13, 'Generał brygady', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1264, null, 18, 'Plutonowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1267, null, 16, 'Szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1270, null, 16, 'Starszy szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1273, null, 7, 'Starszy szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1276, null, 12, 'Generał brygady', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1279, null, 6, 'Starszy chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1282, null, 3, 'Sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1285, null, 7, 'Podpułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1288, null, 3, 'Plutonowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1291, null, 18, 'Starszy chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1294, null, 16, 'Major', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1297, null, 7, 'Starszy szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1300, null, 15, 'Pułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1303, null, 1, 'Chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1306, null, 18, 'Pułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1309, null, 3, 'Starszy kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1312, null, 14, 'Generał', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1315, null, 13, 'Podpułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1318, null, 11, 'Podpułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1321, null, 3, 'Porucznik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1324, null, 19, 'Młodszy podchorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1327, null, 19, 'Generał brygady', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1330, null, 10, 'Chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1333, null, 1, 'Generał dywizji', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1336, null, 7, 'Starszy sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1339, null, 9, 'Pułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1342, null, 11, 'Kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1345, null, 12, 'Starszy chorąży sztabowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1348, null, 16, 'Starszy chorąży sztabowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1351, null, 17, 'Generał broni', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1354, null, 14, 'Kapitan', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1357, null, 2, 'Sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1360, null, 7, 'Pułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1363, null, 2, 'Szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1366, null, 11, 'Pułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1369, null, 16, 'Kapitan', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1372, null, 12, 'Kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1375, null, 1, 'Generał', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1378, null, 15, 'Kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1381, null, 9, 'Podpułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1384, null, 2, 'Porucznik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1387, null, 14, 'Generał', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1390, null, 10, 'Generał broni', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1393, null, 5, 'Podporucznik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1396, null, 7, 'Młodszy podchorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1399, null, 19, 'Chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1402, null, 5, 'Generał broni', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1405, null, 5, 'Kapitan', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1408, null, 1, 'Generał broni', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1411, null, 7, 'Generał dywizji', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1414, null, 4, 'Generał', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1417, null, 8, 'Starszy chorąży sztabowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1420, null, 13, 'Podpułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1423, null, 10, 'Starszy sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1426, null, 19, 'Kapitan', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1429, null, 2, 'Starszy kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1432, null, 2, 'Porucznik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1435, null, 10, 'Starszy sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1438, null, 9, 'Starszy sierżant', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1441, null, 12, 'Generał broni', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1444, null, 4, 'Kapitan', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1447, null, 13, 'Podpułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1450, null, 17, 'Pułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1453, null, 16, 'Podpułkownik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1456, null, 15, 'Podporucznik', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1459, null, 11, 'Młodszy podchorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1462, null, 19, 'Starszy szeregowy', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1465, null, 2, 'Starszy chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1468, null, 7, 'Chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1471, null, 7, 'Major', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1474, null, 19, 'Generał brygady', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1477, null, 13, 'Kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1480, null, 13, 'Starszy kapral', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1483, null, 2, 'Starszy chorąży', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1486, null, 5, 'Generał', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1489, null, 15, 'Generał dywizji', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1492, null, 4, 'Kapitan', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1495, null, 8, 'Generał dywizji', 'false');
insert into soldier (id, team_id, nationality_id, soldier_rank, in_operation) values (1498, null, 11, 'Generał', 'false');

--usuń przypadkowo dodanych sprzątaczy
delete from soldier s
where s.id = (	select p.id 
				from personel p 
				left join "role" r on r.id = p.role_id
				where p.id = s.id and r.role_name = 'SPRZĄTACZ' );

-- check
select count(*) 
from soldier s
left join personel p on s.id = p.id 
left join "role" r on r.id = p.role_id
where r.role_name = 'SPRZĄTACZ';

